# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    # 1. for Github split
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                # define package to repository map
                package:
                    -
                        local_path: 'demo-react-native'
                        split_repository: 'demo-react-native'
                    -
                        local_path: 'demo-react-vite'
                        split_repository: 'demo-react-vite'
                    -
                        local_path: 'demo-taro-react'
                        split_repository: 'demo-taro-react'

        steps:
            -   uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    fetch-depth: 0

            -   name: Configure Git and directories
                run: |
                    # 配置 Git 安全目录
                    git config --global --add safe.directory /github/workspace
                    git config --global --add safe.directory /tmp/monorepo_split/build_directory
                    git config --global --add safe.directory /tmp/monorepo_split/clone_directory

                    git config user.name "mlzgldr"
                    git config user.email "mlzgldr@163.com"
                    
                    # 设置目录权限
                    mkdir -p /tmp/monorepo_split/clone_directory
                    mkdir -p /tmp/monorepo_split/build_directory
                    chmod -R 777 /tmp/monorepo_split

                    # 保存初始目录
                    INITIAL_DIR=$(pwd)

                    # 测试克隆命令
                    echo "克隆仓库"
                    git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/mlzgldr/${{ matrix.package.split_repository }}.git /tmp/monorepo_split/clone_directory

                    echo "检出clone_directory代码"
                    cd /tmp/monorepo_split/clone_directory
                    git config user.name "mlzgldr"
                    git config user.email "mlzgldr@163.com"
                    git fetch

                    # 显示所有分支
                    echo "当前仓库的所有分支："
                    git branch -a

                    # 修改分支检查逻辑
                    if git ls-remote --heads origin ${{ github.ref_name }} | grep -q ${{ github.ref_name }}; then
                        echo "检出已存在的分支 ${{ github.ref_name }}"
                        git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
                    else
                        echo "创建新分支 ${{ github.ref_name }}"
                        git checkout -b ${{ github.ref_name }}
                        
                        # 创建一个初始提交
                        echo "# ${{ matrix.package.split_repository }}" > README.md
                        git add README.md
                        git commit -m "Initial commit"
                        
                        ls -la /tmp/monorepo_split/clone_directory
                        echo "推送新分支 git push origin ${{ github.ref_name }}"
                        git push origin ${{ github.ref_name }}
                    fi

                    echo "复制.git文件到build_directory"
                    mkdir -p /tmp/monorepo_split/build_directory/.git
                    cp -r /tmp/monorepo_split/clone_directory/.git /tmp/monorepo_split/build_directory/

                    # 返回到初始目录
                    cd $INITIAL_DIR

                    # 清理克隆目录
                    rm -rf /tmp/monorepo_split/clone_directory

                    echo "复制package内容到build_directory"
                    cp -ra ${{ github.workspace }}/packages/${{ matrix.package.local_path }}/. /tmp/monorepo_split/build_directory/

                    echo "build_directory里的内容:"
                    ls -la /tmp/monorepo_split/build_directory

                    COMMIT_MSG=$(git show -s --format=%B ${{ github.sha }})

                    cd /tmp/monorepo_split/build_directory
          
                    # 重新设置 Git 用户信息
                    git config user.name "mlzgldr"
                    git config user.email "mlzgldr@163.com"

                    # Check for changes
                    git status
                    git status --porcelain > /tmp/changes.txt
                    
                    if [ -s /tmp/changes.txt ]; then
                        echo "添加变更"
                        git add .
                        
                        echo "提交变更"
                        git commit --message "$COMMIT_MSG"
                        
                        echo "推送修改"
                        git push --quiet origin ${{ github.ref_name }}
                    else
                        echo "没有变更"
                    fi

                    # 返回到初始目录
                    cd $INITIAL_DIR

                    # 清理临时目录
                    rm -rf /tmp/monorepo_split



