name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
# 1. for Github split
GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


jobs:
  packages_split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #- name: Validate composer.json and composer.lock
        #run: composer validate --strict

      - name: Run split script
        run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" GITHUB_SHA="$GITHUB_SHA" php split-repo.php
